# -*- coding: utf-8 -*-
"""Ethical_AI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEN6xJLueb2jNcoeWkhKM1LD02kGfZ3R
"""

!pip install pandas scikit-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

from datasets import load_dataset
import pandas as pd

#load dataset
ds = load_dataset("google/civil_comments")

#convert to pandas
train_df = ds["train"].to_pandas()
test_df = ds["test"].to_pandas()

#create binary labels (toxicity > 0.5)
train_df["label"] = (train_df["toxicity"] > 0.5).astype(int)
test_df["label"] = (test_df["toxicity"] > 0.5).astype(int)

#keep only relevant columns for now
train_df = train_df[["text", "label"]]
test_df = test_df[["text", "label"]]

#drop missing values
train_df = train_df.dropna()
test_df = test_df.dropna()

#preview
train_df.head()

#basic stats
print("Train shape:", train_df.shape)
print(train_df["label"].value_counts())

#define features
X_train = train_df["text"]
y_train = train_df["label"]

X_test = test_df["text"]
y_test = test_df["label"]

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words='english'
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

#train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)


#predict
y_pred = model.predict(X_test_vec)


#evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

#save results
results = pd.DataFrame({
    "text": X_test,
    "true": y_test,
    "pred": y_pred
})

# Errors
errors = results[results['true'] != results['pred']]
errors.head(10)