# -*- coding: utf-8 -*-
"""Ethical_AI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEN6xJLueb2jNcoeWkhKM1LD02kGfZ3R
"""

!pip install pandas scikit-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, recall_score, precision_score, f1_score

from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.calibration import CalibratedClassifierCV

from google.colab import files
import pandas as pd

use_cols = [
    "comment_text", "target",
    "male", "female",
    "black", "white", "asian", "latino",
    "muslim", "christian", "jewish", "hindu", "atheist",
    "bisexual", "heterosexual", "homosexual_gay_or_lesbian"
]

df = pd.read_csv("train.csv", usecols=use_cols)

# Rename
df = df.rename(columns={"comment_text": "text"})

# Label
df["label"] = (df["target"] > 0.5).astype(int)

identity_cols = [
    "male", "female",
    "black", "white", "asian", "latino",
    "muslim", "christian", "jewish", "hindu", "atheist",
    "bisexual", "heterosexual", "homosexual_gay_or_lesbian"
]

df = df[["text", "label"] + identity_cols]

df = df.dropna(subset=["text"])
df[identity_cols] = df[identity_cols].fillna(0)

from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

print("Train shape:", train_df.shape)
print(train_df["label"].value_counts())

#define features
X_train = train_df["text"]
y_train = train_df["label"]

X_test = test_df["text"]
y_test = test_df["label"]

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words='english'
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


#train model
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced"
    ),

    "SVM": CalibratedClassifierCV(
        LinearSVC(class_weight="balanced", max_iter=5000)
    ),

    "Naive Bayes": MultinomialNB()
}


model_results = {}

threshold = 0.3

for name, clf in models.items():
  print(f"\nTraining {name}...")

  clf.fit(X_train_vec, y_train)

  probs = clf.predict_proba(X_test_vec)[:, 1]
  preds = (probs > threshold).astype(int)

  temp_results = pd.DataFrame({
    "text": X_test.values,
    "true": y_test.values,
    "pred": preds,
    "prob": probs
  })

  for col in identity_cols:
    temp_results[col] = test_df[col].values

  model_results[name] = temp_results

  print(f"\n{name} Results")
  print("Accuracy:", accuracy_score(y_test, preds))
  print(classification_report(y_test, preds))

# Errors
#errors = results[results['true'] != results['pred']]
#errors.head(10)

def compute_fpr(df, group_col):
  group = df[df[group_col] > 0.5]
  non_toxic = group[group["true"] == 0]

  if len(non_toxic) == 0:
    return None

  fp = (non_toxic["pred"] == 1).sum()
  return fp / len(non_toxic)


fpr_comparison = []

for model_name, res in model_results.items():
  overall_non_toxic = res[res["true"] == 0]
  overall_fpr = (overall_non_toxic["pred"] == 1).mean()

  for col in identity_cols:
    fpr = compute_fpr(res, col)
    if fpr is not None:
      fpr_comparison.append({
        "model": model_name,
        "identity_group": col,
        "group_fpr": fpr,
        "overall_fpr": overall_fpr,
        "fpr_disparity": fpr - overall_fpr
      })

fpr_df = pd.DataFrame(fpr_comparison)
fpr_df

thresholds = [i / 10 for i in range(1, 10)]

threshold_results = []

for model_name, res in model_results.items():
  probs = res["prob"].values
  true = res["true"].values

  for threshold in thresholds:
    preds = (probs > threshold).astype(int)

    temp = res.copy()
    temp["pred"] = preds

    overall_recall = recall_score(true, preds)
    overall_precision = precision_score(true, preds, zero_division=0)
    overall_f1 = f1_score(true, preds, zero_division=0)

    overall_non_toxic = temp[temp["true"] == 0]
    overall_fpr = (overall_non_toxic["pred"] == 1).mean()

    for col in identity_cols:
      group_fpr = compute_fpr(temp, col)

      if group_fpr is not None:
        threshold_results.append({
          "model": model_name,
          "threshold": threshold,
          "identity_group": col,
          "group_fpr": group_fpr,
          "overall_fpr": overall_fpr,
          "fpr_disparity": group_fpr - overall_fpr,
          "recall": overall_recall,
          "precision": overall_precision,
          "f1": overall_f1
        })

threshold_df = pd.DataFrame(threshold_results)
threshold_df.head()


import matplotlib.pyplot as plt

model_name = "Logistic Regression"
subset = threshold_df[threshold_df["model"] == model_name]

summary = subset.groupby("threshold").agg({
    "recall": "mean",
    "precision": "mean",
    "overall_fpr": "mean"
}).reset_index()

plt.figure(figsize=(8, 5))
plt.plot(summary["threshold"], summary["recall"], marker="o", label="Recall")
plt.plot(summary["threshold"], summary["precision"], marker="o", label="Precision")
plt.plot(summary["threshold"], summary["overall_fpr"], marker="o", label="Overall FPR")
plt.xlabel("Decision Threshold")
plt.ylabel("Score")
plt.title("Threshold Sensitivity: Logistic Regression")
plt.legend()
plt.tight_layout()
plt.savefig("threshold_sensitivity.png", dpi=300, bbox_inches="tight")
plt.show()

import matplotlib.pyplot as plt

for model_name in threshold_df["model"].unique():
    subset = threshold_df[threshold_df["model"] == model_name]

    plt.figure(figsize=(8, 5))

    for group in identity_cols:
        group_data = subset[subset["identity_group"] == group]
        if len(group_data) > 0:
            plt.plot(
                group_data["threshold"],
                group_data["group_fpr"],
                marker="o",
                label=group
            )

    plt.title(f"Threshold Sensitivity: FPR by Identity Group ({model_name})")
    plt.xlabel("Decision Threshold")
    plt.ylabel("False Positive Rate")
    plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
    plt.tight_layout()
    plt.show()

import re

swap_pairs = [
  # Gender
  ("male", "female"),
  ("man", "woman"),
  ("men", "women"),
  ("boy", "girl"),
  ("father", "mother"),
  ("son", "daughter"),
  ("brother", "sister"),
  ("he", "she"),
  ("him", "her"),
  ("his", "hers"),

  # Race / ethnicity
  ("black", "white"),
  ("asian", "latino"),
  ("latina", "asian"),

  # Religion
  ("muslim", "christian"),
  ("jewish", "christian"),
  ("hindu", "christian"),
  ("atheist", "christian"),

  # Sexual orientation
  ("homosexual", "heterosexual"),
  ("bisexual", "heterosexual"),
  ("gay", "straight"),
  ("lesbian", "straight")
]

swaps = {}
for a, b in swap_pairs:
  swaps[a] = b
  swaps[b] = a


def preserve_case(original, replacement):
  if original.isupper():
    return replacement.upper()
  elif original[0].isupper():
    return replacement.capitalize()
  else:
    return replacement


def swap_identity(text):
  def replace(match):
    word = match.group(0)
    lower = word.lower()

    if lower in swaps:
      replacement = swaps[lower]
      return preserve_case(word, replacement)

    # Handle simple plural forms
    if lower.endswith("s"):
      base = lower[:-1]
      if base in swaps:
        replacement = swaps[base] + "s"
        return preserve_case(word, replacement)

    return word

  return re.sub(r"\b\w+\b", replace, text)


# ---- Counterfactual Consistency Test ----
swapped_texts = [swap_identity(t) for t in test_df["text"].tolist()]
X_swapped_vec = vectorizer.transform(swapped_texts)

for model_name, clf in models.items():
  print(f"\nCounterfactual test for {model_name}")

  original_results = model_results[model_name]

  swapped_probs = clf.predict_proba(X_swapped_vec)[:, 1]
  swapped_pred = (swapped_probs > 0.3).astype(int)

  original_results["swapped_pred"] = swapped_pred
  original_results["prediction_flipped"] = (
    original_results["pred"] != original_results["swapped_pred"]
  ).astype(int)

  flip_rate = original_results["prediction_flipped"].mean()

  print(f"Overall flip rate: {flip_rate:.3f}")

  for col in identity_cols:
    group = original_results[original_results[col] > 0.5]
    if len(group) > 0:
      group_flip_rate = group["prediction_flipped"].mean()
      print(f"{col}: {group_flip_rate:.3f} ({len(group)} samples)")

model = models["Logistic Regression"]

feature_names = vectorizer.get_feature_names_out()
coefs = model.coef_[0]

feature_importance = pd.DataFrame({
  "feature": feature_names,
  "coefficient": coefs
})

top_toxic_features = feature_importance.sort_values(
  by="coefficient",
  ascending=False
).head(50)

top_toxic_features

identity_terms = [
  "male", "female", "man", "woman", "men", "women", "boy", "girl",
  "black", "white", "asian", "latino", "latina",
  "muslim", "muslims", "christian", "christians",
  "jewish", "jews", "hindu", "hindus", "atheist", "atheists",
  "bisexual", "heterosexual", "homosexual", "gay", "lesbian", "straight"
]

top_toxic_features["is_identity_term"] = top_toxic_features["feature"].isin(identity_terms)

identity_feature_count = top_toxic_features["is_identity_term"].sum()
identity_feature_percentage = identity_feature_count / len(top_toxic_features)

print("Identity terms in top 50 toxic features:", identity_feature_count)
print("Percentage:", identity_feature_percentage)


def remove_identity_terms(text):
  pattern = r"\b(" + "|".join(identity_terms) + r")\b"
  return re.sub(pattern, "", text, flags=re.IGNORECASE)

X_train_ablate = X_train.apply(remove_identity_terms)
X_test_ablate = X_test.apply(remove_identity_terms)

ablate_vectorizer = TfidfVectorizer(
  max_features=10000,
  stop_words="english"
)

X_train_ablate_vec = ablate_vectorizer.fit_transform(X_train_ablate)
X_test_ablate_vec = ablate_vectorizer.transform(X_test_ablate)

ablate_model = LogisticRegression(max_iter=1000, class_weight="balanced")
ablate_model.fit(X_train_ablate_vec, y_train)

ablate_probs = ablate_model.predict_proba(X_test_ablate_vec)[:, 1]
ablate_pred = (ablate_probs > 0.3).astype(int)

ablate_results = pd.DataFrame({
  "text": X_test.values,
  "true": y_test.values,
  "pred": ablate_pred,
  "prob": ablate_probs
})

for col in identity_cols:
  ablate_results[col] = test_df[col].values

ablation_comparison = []

original_results = model_results["Logistic Regression"]

for col in identity_cols:
  original_fpr = compute_fpr(original_results, col)
  ablated_fpr = compute_fpr(ablate_results, col)

  if original_fpr is not None and ablated_fpr is not None:
    ablation_comparison.append({
      "identity_group": col,
      "original_fpr": original_fpr,
      "ablated_fpr": ablated_fpr,
      "fpr_change": ablated_fpr - original_fpr
    })

ablation_df = pd.DataFrame(ablation_comparison)
ablation_df

"""DISTILLIBERT:"""

!pip install transformers datasets evaluate -q

import torch
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from transformers import TrainingArguments, Trainer
from datasets import Dataset
import numpy as np

train_sample = train_df.sample(n=50000, random_state=42)
test_sample = test_df.sample(n=10000, random_state=42)

train_dataset = Dataset.from_pandas(train_sample[["text", "label"]])
test_dataset = Dataset.from_pandas(test_sample[["text", "label"]])

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

def tokenize(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset = train_dataset.rename_column("label", "labels")
test_dataset = test_dataset.rename_column("label", "labels")

train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])


bert_model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)


training_args = TrainingArguments(
    output_dir="./distilbert_jigsaw",

    # These must match when load_best_model_at_end=True
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=2,
    weight_decay=0.01,

    logging_dir="./logs",
    logging_steps=100,

    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True
)


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision_score(labels, preds, zero_division=0),
        "recall": recall_score(labels, preds, zero_division=0),
        "f1": f1_score(labels, preds, zero_division=0)
    }


trainer = Trainer(
    model=bert_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()


predictions = trainer.predict(test_dataset)

logits = predictions.predictions
probs = torch.softmax(torch.tensor(logits), dim=1)[:, 1].numpy()

distilbert_pred = (probs > 0.3).astype(int)


distilbert_results = pd.DataFrame({
    "text": test_sample["text"].values,
    "true": test_sample["label"].values,
    "pred": distilbert_pred,
    "prob": probs
})

for col in identity_cols:
    distilbert_results[col] = test_sample[col].values


print("DistilBERT Results")
print(classification_report(distilbert_results["true"], distilbert_results["pred"]))

for col in identity_cols:
    fpr = compute_fpr(distilbert_results, col)
    if fpr is not None:
        print(f"{col} FPR: {fpr:.3f}")

model_results["DistilBERT"] = distilbert_results