# -*- coding: utf-8 -*-
"""Ethical_AI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEN6xJLueb2jNcoeWkhKM1LD02kGfZ3R
"""

!pip install pandas scikit-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

from google.colab import files
import pandas as pd

# Upload ONCE, then comment out later
# uploaded = files.upload()

use_cols = [
    "comment_text", "target",
    "male", "female",
    "black", "white",
    "muslim", "christian", "jewish"
]

df = pd.read_csv("train.csv", usecols=use_cols)

# Rename
df = df.rename(columns={"comment_text": "text"})

# Label
df["label"] = (df["target"] > 0.5).astype(int)

identity_cols = [
    "male", "female",
    "black", "white",
    "muslim", "christian", "jewish"
]

df = df[["text", "label"] + identity_cols]

df = df.dropna(subset=["text"])
df[identity_cols] = df[identity_cols].fillna(0)

from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

print("Train shape:", train_df.shape)
print(train_df["label"].value_counts())

#define features
X_train = train_df["text"]
y_train = train_df["label"]

X_test = test_df["text"]
y_test = test_df["label"]

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words='english'
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


#train model
model = LogisticRegression(max_iter=1000, class_weight="balanced")
model.fit(X_train_vec, y_train)


#predict
probs = model.predict_proba(X_test_vec)[:, 1]
y_pred = (probs > 0.3).astype(int)


#evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

#save results
results = pd.DataFrame({
    "text": X_test,
    "true": y_test,
    "pred": y_pred
})

#attach all identity columns at once
for col in identity_cols:
  results[col] = test_df[col].values

# Errors
errors = results[results['true'] != results['pred']]
errors.head(10)

def compute_fpr(df, group_col):
  group = df[df[group_col] > 0.5]  # subgroup
  non_toxic = group[group["true"] == 0]

  if len(non_toxic) == 0:
      return None

  fp = sum((non_toxic["pred"] == 1))
  return fp / len(non_toxic)


for col in identity_cols:
  fpr = compute_fpr(results, col)
  print(f"{col} FPR: {fpr}")

def swap_identity(text):
  swaps = {
      "he": "she", "she": "he",
      "muslim": "christian", "christian": "muslim",
      "black": "white", "white": "black"
  }
  words = text.split()
  new_words = []
  for w in words:
    lower = w.lower()
    if lower in swaps:
      replacement = swaps[lower]
      if w[0].isupper():
          replacement = replacement.capitalize()
      new_words.append(replacement)
    else:
      new_words.append(w)
  return " ".join(new_words)


# ---- Counterfactual Consistency Test ----
test_texts = test_df["text"].tolist()
swapped_texts = [swap_identity(t) for t in test_texts]

X_swapped_vec = vectorizer.transform(swapped_texts)
swapped_probs = model.predict_proba(X_swapped_vec)[:, 1]
y_swapped_pred = (swapped_probs > 0.3).astype(int)

results["swapped_pred"] = y_swapped_pred
results["prediction_flipped"] = (results["pred"] != results["swapped_pred"]).astype(int)

flip_rate = results["prediction_flipped"].mean()
print(f"\nCounterfactual flip rate: {flip_rate:.3f}")
print(f"({flip_rate*100:.1f}% of predictions changed after identity term swapping)\n")

print("Flip rates by identity group:")
for col in identity_cols:
    group = results[results[col] > 0.5]
    if len(group) > 0:
        group_flip_rate = group["prediction_flipped"].mean()
        print(f"  {col}: {group_flip_rate:.3f} ({len(group)} samples)")

import matplotlib.pyplot as plt

# FPR Bar Chart
fpr_scores = {}
for col in identity_cols:
    fpr = compute_fpr(results, col)
    if fpr is not None:
        fpr_scores[col] = fpr

plt.figure(figsize=(8, 4))
plt.bar(fpr_scores.keys(), fpr_scores.values(), color="steelblue")
plt.axhline(y=results[results["true"]==0]["pred"].mean(),
            color="red", linestyle="--", label="Overall FPR")
plt.title("False Positive Rate by Identity Group")
plt.ylabel("FPR")
plt.xlabel("Identity Group")
plt.legend()
plt.tight_layout()
plt.savefig("fpr_by_group.png", dpi=150)
plt.show()

# Flip Rate Bar Chart
flip_by_group = {}
for col in identity_cols:
    group = results[results[col] > 0.5]
    if len(group) > 0:
        flip_by_group[col] = group["prediction_flipped"].mean()

plt.figure(figsize=(8, 4))
plt.bar(flip_by_group.keys(), flip_by_group.values(), color="coral")
plt.title("Counterfactual Flip Rate by Identity Group")
plt.ylabel("Flip Rate")
plt.xlabel("Identity Group")
plt.tight_layout()
plt.savefig("flip_rate_by_group.png", dpi=150)
plt.show()